#!/usr/bin/env python3.10
import sys

def usage():
    print("console usage:")
    print("--repl/-r start read eval print loop")

def repl():
    programExit = False
    while not programExit:
        query = input("REPL>> ")
        


try:
    if sys.argv[1] == "--repl" or "-r":
        repl()
except IndexError:
    usage()